FROM ghcr.io/mlflow/mlflow:v2.8.1

# Install postgresql client dependencies and psycopg2
# Note: ghcr.io/mlflow/mlflow is based on Python (Debian/Slim usually), so we might need gcc/libpq-dev
USER root
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install psycopg2-binary
